<?php

namespace Vlad\HelloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VladRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VladRepository extends EntityRepository
{
}
